params ["_pos","_building"];
private _mrkid = format["%1-whouse",_pos];
createMarker [_mrkid,_pos];
_mrkid setMarkerShape "ICON";
_mrkid setMarkerType "ot_Warehouse";
_mrkid setMarkerColor "ColorWhite";
_mrkid setMarkerAlpha 1;
private _xc = format["%1", floor(_pos select 0)];
private _yc = format["%1", floor(_pos select 1)];
while {count _xc < 5} do { _xc = format ["%1%2", "0", _xc]; };
while {count _yc < 5} do { _yc = format ["%1%2", "0", _yc]; };
private _wid = format ["%1%2", _xc, _yc];
OT_allWarehouses pushbackUnique [_pos,_wid];
publicVariable "OT_allWarehouses";
//_building addEventHandler ["Dammaged", OT_fnc_buildingDamagedHandler];
_building addEventHandler ["Hit", OT_fnc_buildingHitHandler];